AllCops:
  Exclude:
    - lib/gitlab_build_output/core_ext/**/*
    - lib/gitlab_build_output/ansi2html.rb

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
    - gitlab-build-output.gemspec
